### ISSUE TITLE
Draconium plate ?

### ISSUE THREAD

**Issue by LokyLive** [PanSzelescik/moreplates#1]
Maybe i will say something stupid but i don't find More plates for Draconic evolution in 1.10.2 ,is it for next update ?
Will you release an other mod for Gear ?

**Comment by PanSzelescik** [comment]
I can do it, but I need some time. Maybe the gears will join to More Plates.

**Comment by PanSzelescik** [comment]
Plates for Draconic Evolution (Draconium and awakened Draconium) are in version 6.0 and up in 1.10.2 version. For 1.11.2 I add if Draconic Evolution will be available for 1.11.2. Please read changelogs

**Comment by PanSzelescik** [comment]
Added gears in 1.10.2-8.0 and in a moment in 1.11.2-8.0
