### ISSUE TITLE
Missing Item names.

### ISSUE THREAD

**Issue by Fundryi** [PanSzelescik/moreplates#11]
All Mystical Agriculture Gear/Plates have the "code" name.
Also if you choose the Language "English (US)" instead of "English (United States)" your items have all the default "coded" name.
Idk why this is a thing but there are no differents, right?

**Comment by PanSzelescik** [comment]
I have to check it out

**Comment by PanSzelescik** [comment]
Please
Minecraft version
Forge version
MA version
Cucumber version

**Comment by Fundryi** [comment]
MC: 1.12.1
Forge-14.22.0.2457
MA: 1.12.x-2.2.0.2456
Cumber: 1.12-1.0.0

**Comment by PanSzelescik** [comment]
Interesting...
![2017-08-18_14 19 11](https://user-images.githubusercontent.com/26679785/29458620-535c1ff8-8420-11e7-9fed-ad5d0aa0f188.png)

**Comment by Fundryi** [comment]
Good so it's not only me ;) xD

**Comment by PanSzelescik** [comment]
https://github.com/PanSzelescik/moreplates/blob/1.12/src/main/resources/assets/moreplates/lang/en_us.lang
But the translation is so I do not understand why it does not work with Mystical Agriculture

**Comment by PanSzelescik** [comment]
From what I see at 1.12 the same thing

**Comment by Fundryi** [comment]
Looks like forge change something from 1.11 to 1.12

**Comment by PanSzelescik** [comment]
At 1.12 mod was completely rewritten

**Comment by PanSzelescik** [comment]
Somehow with the Tinkers, Draconic, Refined Storage there are no problems

**Comment by Fundryi** [comment]
It's  a pretty weird bug.

**Comment by PanSzelescik** [comment]
Mystical Agradditions also has no translations, probably the project red would not have it either

**Comment by PanSzelescik** [comment]
Fixed https://github.com/PanSzelescik/moreplates/commit/9a0ff46103b6c561f20f55b7c6e285e885d45933
xd

**Comment by Fundryi** [comment]
So what was it? Also will you push the updated now out :P?

**Comment by Fundryi** [comment]
Loool I just saw it xD

**Comment by PanSzelescik** [comment]
Update here: https://minecraft.curseforge.com/projects/moreplates/files/2466223

**Comment by Fundryi** [comment]
Thank you!
