### ISSUE TITLE
[Suggestion] ExtraUtilities2 Ingots

### ISSUE THREAD

**Issue by Fundryi** [PanSzelescik/moreplates#14]
Demon Ingot
Enchanted Ingot
Evil Infused Iron Ingot
Would be cool :)

**Comment by PanSzelescik** [comment]
Yes, it was even in my plans, but I have not added yet

**Comment by PanSzelescik** [comment]
Added in 2.5.0

**Comment by Gnimacz** [comment]
how does one make an evil infused iron ingot?
