### ISSUE TITLE
[Suggestion]Other metals from other mods

### ISSUE THREAD

**Issue by TokkenGmr** [PanSzelescik/moreplates#2]
I was wondering if there were plans for things like:

Botania: Manasteel, Terrasteel and Elementium 
Tinkers Construct: Ardite, Cobalt, Manyullyn maybe Knightslime

**Comment by PanSzelescik** [comment]
Yes, it is in the plans. New plates and gears from other mods coming soon.

**Comment by PanSzelescik** [comment]
I added botania support in 9.0, tinkers construct support coming soon in 10.0

**Comment by TokkenGmr** [comment]
I just want to say think you!! Looking forward to all that you may add in the future

**Comment by PanSzelescik** [comment]
Tinkers' Construct items added in 10.0.
