### ISSUE TITLE
Processing rework

### ISSUE THREAD

**Issue by LokyLive** [PanSzelescik/moreplates#28]
Hey i'm working on a new modpack and i'm searching a mod to provides tiny pile ore , rocky ore for redstone ect... 
I know you're working on Gear, plate ..... so why not an Harder ore processing ?  xD

**Comment by PanSzelescik** [comment]
Harder ore processing? What do you mean?

**Comment by LokyLive** [comment]
like the old gregtech style 
for example redstone ore > rocky redstone dust > 9x tiny pile redstone dust > 1x redstone dust
same thing for all Ore ( diamond,iron, quartz, coal ,black quartz , osmium..... )

**Comment by PanSzelescik** [comment]
I have not planned it yet, but I will think later

**Comment by PanSzelescik** [comment]
I have plans to add rods and nuggets, but I need help with textures :/

**Comment by WindFox** [comment]
Just wondering if there will be rods for Thermal Foundation metals.

**Comment by PanSzelescik** [comment]
I have plans to add Thermal Foundation rods + Iron and Gold
