### ISSUE TITLE
Config to disable crafting table recipes for gears

### ISSUE THREAD

**Issue by Peach774** [PanSzelescik/moreplates#45]
I am making a custom pack and would love a way to remove all of the crafting table recipes for gears from this mod.

**Comment by PanSzelescik** [comment]
For all gears? Okay

**Comment by PanSzelescik** [comment]
I also added it to Plates and Rods

**Comment by Peach774** [comment]
Wait, does this also disable their recipes in things like the Immersive Engineering metal former? I was hoping for a config that just disables crafting table recipes so you need to use machines.

**Comment by PanSzelescik** [comment]
To disable recipes in Metal Press (Immersive Engineering) you can use:
`B:"Immersive Engineering"=true ---> false`
Not all, because IE adds recipes automatically via OreDict

To disable recipes in Metal Former & Block Cutting Machine (IC2) you can use:
`B:"Industrial Craft 2"=true ---> false`

**Comment by Peach774** [comment]
and this new change will mean I can disable recipes in the crafting table?

**Comment by PanSzelescik** [comment]
Yes
