### ISSUE TITLE
Diamond rods?

### ISSUE THREAD

**Issue by VariableVixen** [PanSzelescik/moreplates#50]
A lot of materials only seem to have some forms added by this mod, but I just ran into this problem while working on a custom modpack. I need diamond rods for some tool recipes, but I only have plates, gears, nuggets, and gems for diamond. Would it be possible to implement all of plate/rod/gear(/nugget?) for all of the materials this mod works with?

**Comment by PanSzelescik** [comment]
Yes, but I must spend a lot of time creating textures

**Comment by VariableVixen** [comment]
Oh! I actually used ContentTweaker to make one... the texture's hardly _great_ since I'm no artist, but would you like a copy to at least look at?
